=== pablolarafalso-create/TrabajoIntermodular/data/data.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="foodTracker">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="usuarios">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="usuario" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id_user" type="xs:int"/>
                    <xs:element name="nombre" type="xs:string"/>
                    <xs:element name="apellidos" type="xs:string"/>
                    <xs:element name="email" type="xs:string"/>
                    <xs:element name="contraseña" type="xs:string"/>
                    <xs:element name="fecha_nacimiento" type="xs:date"/>
                    <xs:element name="altura" type="xs:decimal"/>
                    <xs:element name="peso" type="xs:decimal"/>
                    <xs:element name="fechaCreacion" type="xs:dateTime"/>
                    <xs:element name="racha" type="xs:int"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="objetivos_diarios">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="objetivo_diario" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id_user" type="xs:int"/>
                    <xs:element name="kcal" type="xs:int"/>
                    <xs:element name="proteinas" type="xs:decimal"/>
                    <xs:element name="carbohidratos" type="xs:decimal"/>
                    <xs:element name="grasas" type="xs:decimal"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="registros_diarios">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="registro_diario" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="registro_id" type="xs:int"/>
                    <xs:element name="hora_registro" type="xs:dateTime"/>
                    <xs:element name="id_user" type="xs:int"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="comidas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="comida" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id_comida" type="xs:int"/>
                    <xs:element name="tipo_comida" type="xs:string"/>
                    <xs:element name="visiblesn" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="alimentos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="alimento" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id_alimento" type="xs:int"/>
                    <xs:element name="nombre" type="xs:string"/>
                    <xs:element name="kcal" type="xs:int"/>
                    <xs:element name="proteinas" type="xs:decimal"/>
                    <xs:element name="carbohidratos" type="xs:decimal"/>
                    <xs:element name="grasas" type="xs:decimal"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="registro_diario_comidas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="registro_diario_comida" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id_comida" type="xs:int"/>
                    <xs:element name="registro_id" type="xs:int"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="comida_alimentos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="comida_alimento" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id_comida" type="xs:int"/>
                    <xs:element name="id_alimento" type="xs:int"/>
                    <xs:element name="cantidad" type="xs:int"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== pablolarafalso-create/TrabajoIntermodular/data/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<alimentos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="data.xsd">
    
  <alimento>
    <id_alimento>1</id_alimento>
    <nombre>Avena</nombre>
    <kcal>389</kcal><proteinas>16.9</proteinas>
    <carbohidratos>66.3</carbohidratos>
    <grasas>6.9</grasas>
  </alimento>

  <alimento>
    <id_alimento>2</id_alimento>
    <nombre>Arroz integral</nombre>
    <kcal>111</kcal>
    <proteinas>2.6</proteinas>
    <carbohidratos>23.0</carbohidratos>
    <grasas>0.9</grasas>
  </alimento>

  <alimento>
    <id_alimento>3</id_alimento>
    <nombre>Quinoa</nombre>
    <kcal>120</kcal><proteinas>4.4</proteinas>
    <carbohidratos>21.3</carbohidratos>
    <grasas>1.9</grasas>
  </alimento>

  <alimento>
    <id_alimento>4</id_alimento>
    <nombre>Cuscús</nombre>
    <kcal>112</kcal><proteinas>3.8</proteinas>
    <carbohidratos>23.2</carbohidratos>
    <grasas>0.2</grasas>
  </alimento>

  <alimento>
    <id_alimento>5</id_alimento>
    <nombre>Pan integral</nombre>
    <kcal>247</kcal><proteinas>8.5</proteinas>
    <carbohidratos>41.0</carbohidratos>
    <grasas>4.2</grasas>
  </alimento>

  <alimento>
    <id_alimento>6</id_alimento>
    <nombre>Pasta integral</nombre>
    <kcal>124</kcal><proteinas>5.0</proteinas>
    <carbohidratos>25.0</carbohidratos>
    <grasas>1.1</grasas>
  </alimento>

  <alimento>
    <id_alimento>7</id_alimento>
    <nombre>Maíz</nombre>
    <kcal>96</kcal><proteinas>3.4</proteinas>
    <carbohidratos>21.0</carbohidratos>
    <grasas>1.5</grasas>
  </alimento>

  <alimento>
    <id_alimento>8</id_alimento>
    <nombre>Mijo</nombre>
    <kcal>119</kcal><proteinas>3.5</proteinas>
    <carbohidratos>23.7</carbohidratos>
    <grasas>1.0</grasas>
  </alimento>

  <alimento>
    <id_alimento>9</id_alimento>
    <nombre>Amaranto</nombre>
    <kcal>102</kcal><proteinas>3.8</proteinas>
    <carbohidratos>19.0</carbohidratos>
    <grasas>1.6</grasas>
  </alimento>

  <alimento>
    <id_alimento>10</id_alimento>
    <nombre>Trigo integral</nombre>
    <kcal>340</kcal><proteinas>13.2</proteinas>
    <carbohidratos>72.0</carbohidratos>
    <grasas>2.5</grasas>
  </alimento>

  <alimento>
    <id_alimento>11</id_alimento>
    <nombre>Pechuga de pollo</nombre>
    <kcal>165</kcal><proteinas>31.0</proteinas>
    <carbohidratos>0.0</carbohidratos>
    <grasas>3.6</grasas>
  </alimento>

  <alimento>
    <id_alimento>12</id_alimento>
    <nombre>Pavo</nombre>
    <kcal>135</kcal><proteinas>29.0</proteinas>
    <carbohidratos>0.0</carbohidratos>
    <grasas>1.0</grasas>
  </alimento>

  <alimento>
    <id_alimento>13</id_alimento>
    <nombre>Carne de res magra</nombre>
    <kcal>217</kcal><proteinas>26.0</proteinas>
    <carbohidratos>0.0</carbohidratos>
    <grasas>12.0</grasas>
  </alimento>

  <alimento>
    <id_alimento>14</id_alimento>
    <nombre>Cerdo magro</nombre>
    <kcal>242</kcal><proteinas>27.0</proteinas>
    <carbohidratos>0.0</carbohidratos>
    <grasas>14.0</grasas>
  </alimento>

  <alimento>
    <id_alimento>15</id_alimento>
    <nombre>Salmón</nombre>
    <kcal>208</kcal><proteinas>20.0</proteinas>
    <carbohidratos>0.0</carbohidratos>
    <grasas>13.0</grasas>
  </alimento>

  <alimento>
    <id_alimento>16</id_alimento>
    <nombre>Atún</nombre>
    <kcal>132</kcal><proteinas>28.0</proteinas>
    <carbohidratos>0.0</carbohidratos>
    <grasas>1.0</grasas>
  </alimento>

  <alimento>
    <id_alimento>17</id_alimento>
    <nombre>Sardinas</nombre>
    <kcal>208</kcal><proteinas>25.0</proteinas>
    <carbohidratos>0.0</carbohidratos>
    <grasas>11.0</grasas>
  </alimento>

  <alimento>
    <id_alimento>18</id_alimento>
    <nombre>Huevo</nombre>
    <kcal>155</kcal><proteinas>13.0</proteinas>
    <carbohidratos>1.1</carbohidratos>
    <grasas>11.0</grasas>
  </alimento>

  <alimento>
    <id_alimento>19</id_alimento>
    <nombre>Clara de huevo</nombre>
    <kcal>52</kcal><proteinas>11.0</proteinas>
    <carbohidratos>0.7</carbohidratos>
    <grasas>0.2</grasas>
  </alimento>

  <alimento>
    <id_alimento>20</id_alimento>
    <nombre>Leche</nombre>
    <kcal>42</kcal><proteinas>3.4</proteinas>
    <carbohidratos>5.0</carbohidratos>
    <grasas>1.0</grasas>
  </alimento>

  <alimento>
    <id_alimento>21</id_alimento>
    <nombre>Lentejas</nombre>
    <kcal>116</kcal><proteinas>9.0</proteinas>
    <carbohidratos>20.0</carbohidratos>
    <grasas>0.4</grasas>
  </alimento>

  <alimento>
    <id_alimento>22</id_alimento>
    <nombre>Garbanzos</nombre>
    <kcal>164</kcal><proteinas>8.9</proteinas>
    <carbohidratos>27.0</carbohidratos>
    <grasas>2.6</grasas>
  </alimento>

  <alimento>
    <id_alimento>23</id_alimento>
    <nombre>Alubias negras</nombre>
    <kcal>132</kcal><proteinas>8.9</proteinas>
    <carbohidratos>23.7</carbohidratos>
    <grasas>0.5</grasas>
  </alimento>

  <alimento>
    <id_alimento>24</id_alimento>
    <nombre>Alubias rojas</nombre>
    <kcal>127</kcal><proteinas>8.7</proteinas>
    <carbohidratos>22.8</carbohidratos>
    <grasas>0.5</grasas>
  </alimento>

  <alimento>
    <id_alimento>25</id_alimento>
    <nombre>Soja</nombre>
    <kcal>173</kcal><proteinas>16.6</proteinas>
    <carbohidratos>9.9</carbohidratos>
    <grasas>9.0</grasas>
  </alimento>

  <alimento>
    <id_alimento>26</id_alimento>
    <nombre>Tofu</nombre>
    <kcal>76</kcal><proteinas>8.0</proteinas>
    <carbohidratos>1.9</carbohidratos>
    <grasas>4.8</grasas>
  </alimento>

  <alimento>
    <id_alimento>27</id_alimento>
    <nombre>Tempeh</nombre>
    <kcal>193</kcal><proteinas>20.0</proteinas>
    <carbohidratos>9.0</carbohidratos>
    <grasas>11.0</grasas>
  </alimento>

  <alimento>
    <id_alimento>28</id_alimento>
    <nombre>Edamame</nombre>
    <kcal>121</kcal><proteinas>11.0</proteinas>
    <carbohidratos>10.0</carbohidratos>
    <grasas>5.0</grasas>
  </alimento>

  <alimento>
    <id_alimento>29</id_alimento>
    <nombre>Habas</nombre>
    <kcal>88</kcal><proteinas>7.6</proteinas>
    <carbohidratos>18.7</carbohidratos>
    <grasas>0.7</grasas>
  </alimento>

  <alimento>
    <id_alimento>30</id_alimento>
    <nombre>Guisantes</nombre>
    <kcal>81</kcal><proteinas>5.4</proteinas>
    <carbohidratos>14.0</carbohidratos>
    <grasas>0.4</grasas>
  </alimento>

  <alimento>
    <id_alimento>31</id_alimento>
    <nombre>Brócoli</nombre>
    <kcal>55</kcal><proteinas>3.7</proteinas>
    <carbohidratos>11.0</carbohidratos>
    <grasas>0.6</grasas>
  </alimento>

  <alimento>
    <id_alimento>32</id_alimento>
    <nombre>Espinaca</nombre>
    <kcal>23</kcal><proteinas>2.9</proteinas>
    <carbohidratos>3.6</carbohidratos>
    <grasas>0.4</grasas>
  </alimento>

  <alimento>
    <id_alimento>33</id_alimento>
    <nombre>Lechuga</nombre>
    <kcal>15</kcal><proteinas>1.4</proteinas>
    <carbohidratos>2.9</carbohidratos>
    <grasas>0.2</grasas>
  </alimento>

  <alimento>
    <id_alimento>34</id_alimento>
    <nombre>Tomate</nombre>
    <kcal>18</kcal><proteinas>0.9</proteinas>
    <carbohidratos>3.9</carbohidratos>
    <grasas>0.2</grasas>
  </alimento>

  <alimento>
    <id_alimento>35</id_alimento>
    <nombre>Pepino</nombre>
    <kcal>16</kcal><proteinas>0.7</proteinas>
    <carbohidratos>3.6</carbohidratos>
    <grasas>0.1</grasas>
  </alimento>

  <alimento>
    <id_alimento>36</id_alimento>
    <nombre>Zanahoria</nombre>
    <kcal>41</kcal><proteinas>0.9</proteinas>
    <carbohidratos>10.0</carbohidratos>
    <grasas>0.2</grasas>
  </alimento>

  <alimento>
    <id_alimento>37</id_alimento>
    <nombre>Pimiento rojo</nombre>
    <kcal>31</kcal><proteinas>1.0</proteinas>
    <carbohidratos>6.0</carbohidratos>
    <grasas>0.3</grasas>
  </alimento>

  <alimento>
    <id_alimento>38</id_alimento>
    <nombre>Pimiento verde</nombre>
    <kcal>20</kcal><proteinas>0.9</proteinas>
    <carbohidratos>4.6</carbohidratos>
    <grasas>0.2</grasas>
  </alimento>

  <alimento>
    <id_alimento>39</id_alimento>
    <nombre>Calabacín</nombre>
    <kcal>17</kcal><proteinas>1.2</proteinas>
    <carbohidratos>3.1</carbohidratos>
    <grasas>0.3</grasas>
  </alimento>

  <alimento>
    <id_alimento>40</id_alimento>
    <nombre>Berenjena</nombre>
    <kcal>25</kcal><proteinas>1.0</proteinas>
    <carbohidratos>6.0</carbohidratos>
    <grasas>0.2</grasas>
  </alimento>

  <alimento>
    <id_alimento>41</id_alimento>
    <nombre>Cebolla</nombre>
    <kcal>40</kcal><proteinas>1.1</proteinas>
    <carbohidratos>9.3</carbohidratos>
    <grasas>0.1</grasas>
  </alimento>

  <alimento>
    <id_alimento>42</id_alimento>
    <nombre>Ajo</nombre>
    <kcal>149</kcal><proteinas>6.4</proteinas>
    <carbohidratos>33.1</carbohidratos>
    <grasas>0.5</grasas>
  </alimento>

  <alimento>
    <id_alimento>43</id_alimento>
    <nombre>Coliflor</nombre>
    <kcal>25</kcal><proteinas>1.9</proteinas>
    <carbohidratos>5.0</carbohidratos>
    <grasas>0.3</grasas>
  </alimento>

  <alimento>
    <id_alimento>44</id_alimento>
    <nombre>Repollo</nombre>
    <kcal>25</kcal><proteinas>1.3</proteinas>
    <carbohidratos>6.0</carbohidratos>
    <grasas>0.1</grasas>
  </alimento>

  <alimento>
    <id_alimento>45</id_alimento>
    <nombre>Judías verdes</nombre>
    <kcal>31</kcal><proteinas>1.8</proteinas>
    <carbohidratos>7.0</carbohidratos>
    <grasas>0.2</grasas>
  </alimento>

  <alimento>
    <id_alimento>46</id_alimento>
    <nombre>Espárragos</nombre>
    <kcal>20</kcal><proteinas>2.2</proteinas>
    <carbohidratos>3.9</carbohidratos>
    <grasas>0.1</grasas>
  </alimento>

  <alimento>
    <id_alimento>47</id_alimento>
    <nombre>Champiñones</nombre>
    <kcal>22</kcal><proteinas>3.1</proteinas>
    <carbohidratos>3.3</carbohidratos>
    <grasas>0.3</grasas>
  </alimento>

  <alimento>
    <id_alimento>48</id_alimento>
    <nombre>Setas</nombre>
    <kcal>28</kcal><proteinas>3.6</proteinas>
    <carbohidratos>4.3</carbohidratos>
    <grasas>0.5</grasas>
  </alimento>

  <alimento>
    <id_alimento>49</id_alimento>
